# Generated by Django on 2018-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0002_kara_status")]
    replaces = [("playlist", "0003_auto_20180402_1443")]

    operations = [
        migrations.AlterField(
            model_name="karastatus",
            name="status",
            field=models.CharField(
                default="play",
                max_length=5,
                choices=[("stop", "Stop"), ("play", "Play"), ("pause", "Pause")],
            ),
        )
    ]
