# Generated by Django on 2018-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0003_kara_status_status")]
    replaces = [("playlist", "0004_auto_20180402_1449")]

    operations = [
        migrations.AddField(
            model_name="playlistentry",
            name="date_played",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="playlistentry",
            name="was_played",
            field=models.BooleanField(default=False),
        ),
    ]
