# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20180402_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistentry',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='playlistentry',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1,
                                              editable=False),
            preserve_default=False,
        ),
    ]
