# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20180402_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistentry',
            name='had_error',
            field=models.BooleanField(default=False),
        ),
    ]
