# Generated by Django 1.11.13 on 2018-07-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlist", "0005_playlist_entry_order")]
    replaces = [("playlist", "0006_auto_20180722_1512")]

    operations = [migrations.RenameModel(old_name="KaraStatus", new_name="Karaoke")]
