# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlist", "0005_auto_20180610_1705")]

    operations = [migrations.RenameModel(old_name="KaraStatus", new_name="Karaoke")]
