# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0006_auto_20180722_1512")]

    operations = [
        migrations.AddField(
            model_name="karaoke",
            name="date_stop",
            field=models.DateTimeField(null=True),
        )
    ]
