# Generated by Django 1.11.13 on 2018-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0006_karaoke")]

    operations = [
        migrations.AddField(
            model_name="karaoke",
            name="date_stop",
            field=models.DateTimeField(null=True),
        )
    ]
