# Generated by Django 1.11.13 on 2018-07-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0007_karaoke_date_stop")]
    replaces = [("playlist", "0008_playererror")]

    operations = [
        migrations.CreateModel(
            name="PlayerError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_message", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playlist.PlaylistEntry",
                    ),
                ),
            ],
        )
    ]
