# Generated by Django 1.11.15 on 2019-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0008_player_error")]
    replaces = [("playlist", "0009_auto_20190106_0734")]

    operations = [
        migrations.RemoveField(model_name="karaoke", name="status"),
        migrations.AddField(
            model_name="karaoke",
            name="can_add_to_playlist",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="karaoke",
            name="ongoing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="karaoke",
            name="player_play_next_song",
            field=models.BooleanField(default=True),
        ),
    ]
