# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0009_auto_20190106_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistentry",
            name="use_instrumental",
            field=models.BooleanField(default=False),
        ),
    ]
