# Generated by Django 2.2.11 on 2020-03-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0009_karaoke_boolean_fields"),
    ]
    replaces = [
        ("playlist", "0010_auto_20200329_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistentry",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
        migrations.AlterField(
            model_name="playlistentry",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="playlistentry",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="library.Song"
            ),
        ),
    ]
