# Generated by Django 2.2.12 on 2020-04-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0010_auto_20200329_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistentry",
            name="use_instrumental",
            field=models.BooleanField(default=False),
        ),
    ]
