# Generated by Django 2.2.12 on 2020-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0011_karaoke_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistentry",
            name="use_instrumental",
            field=models.BooleanField(default=False),
        ),
    ]
