# Generated by Django 2.2.17 on 2021-09-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0012_playlist_entry_use_instrumental"),
    ]

    operations = []
