# Generated by Django 2.2.17 on 2021-09-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0012_playlist_entry_use_instrumental"),
    ]

    # NOTE This migration is artificial as it is triggered by the use of the
    # in-memory player, that uses Django fields.
    # NOTE This migration was moved to 0017.
    operations = []
