# Generated by Django 5.2.12 on 2026-06-21 21:53

import datetime

import django.db.models.deletion
from django.db import migrations, models

import internal.cache_model


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0016_playlist_entry_date_play"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "karaoke",
                    internal.cache_model.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="playlist.karaoke",
                    ),
                ),
                ("timing", models.DurationField(default=datetime.timedelta(0))),
                ("paused", models.BooleanField(default=False)),
                ("in_transition", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
    ]
