version: 1.5.0-dev-{build}

build: false

# restrict to branches
branches:
  only:
  - develop
  - master

# enable cache for Python dependencies
cache:
  - "%LOCALAPPDATA%\\pip\\Cache"

environment:
  # setup special environment variable for Appveyor CI test environment
  # it is used to disable some tests that can be harmful in this context
  APPVEYOR_CI_ENV: 1

  # setup tests matrix
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

# check current python version
init:
  - "py -%PYTHON_VERSION% --version"

# command to install system and python dependencies
install:
  # install dependencies for test
  - "py -%PYTHON_VERSION% -m pip install -r requirements.txt"

# command to run tests
# the current working directory is not reinitialized between commands
test_script:
  - "cd dakara_server"

  # run tests
  - "py -%PYTHON_VERSION% -m pytest -v"

  - "cd .."

  # run code formatting tests
  - "if NOT %PYTHON_VERSION% == 3.5 (py -%PYTHON_VERSION% -m  black . --check)"
  - "py -%PYTHON_VERSION% -m flake8"
