version: 1.7.0-dev-{build}

build: false

# restrict to branches
branches:
  only:
  - develop
  - master

# enable cache for Python dependencies
cache:
  - "%LOCALAPPDATA%\\pip\\Cache"

environment:
  # setup special environment variable for Appveyor CI test environment
  # it is used to disable some tests that can be harmful in this context
  APPVEYOR_CI_ENV: 1

  # setup tests matrix
  matrix:
    - PYTHON: "3.6"
    - PYTHON: "3.7"
    - PYTHON: "3.8"

# check current python version
init:
  - "py -%PYTHON% --version"

# command to install system and python dependencies
install:
  # install dependencies for test
  - "py -%PYTHON% -m pip install -r requirements.txt"

# command to run tests
# the current working directory is not reinitialized between commands
test_script:
  # run tests
  - "py -%PYTHON% -m coverage run -m pytest -v"

  # run code formatting tests
  - "py -%PYTHON% -m  black . --check"
  - "py -%PYTHON% -m flake8"

# commands to manage tests results
after_test:
  # show coverage stats
  - "py -%PYTHON% -m coverage report -m"

  # upload coverage stats to codecov.io
  # coverage must be called manually
  # codecov token is stored in appveyor settings
  - "py -%PYTHON% -m coverage xml"
  - "py -%PYTHON% -m codecov -X gcov --file coverage.xml"
