---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pytest-check
        name: Unit tests
        entry: pytest --no-cov
        language: system
        pass_filenames: false
      - id: isort-check
        name: Check imports order
        entry: isort . --check
        language: system
        pass_filenames: false
      - id: black-check
        name: Check code formatting
        entry: black . --check
        language: system
        pass_filenames: false
      - id: ruff-check
        name: Check code quality
        entry: ruff check .
        language: system
        pass_filenames: false
      - id: yamllint-check
        name: Check YAML files quality
        entry: yamllint .
        language: system
        pass_filenames: false
