language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - (cd dakara_server && ./manage.py test -v 2)
  - flake8
