language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# enable cache for Python dependencies
cache: pip

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  # run tests
  - python -m coverage run -m pytest -v

  # run code formatting tests
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check; fi
  - flake8

# commands to manage tests results
after_script:
  # show coverage stats
  - python -m coverage report -m

  # upload coverage stats to codecov.io
  # codecov token is stored in travis settings
  - python -m codecov -X gcov
