language: python
python:
  - "3.5"
  - "3.6"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - (cd dakara_server && ./manage.py test --settings=dakara_server.settings.test -v 2)
  - (cd dakara_server && pytest -v)
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check; fi
  - flake8
