version: 1.2.0-{build}

build: false

# restrict to branches
branches:
  only:
  - develop
  - master

environment:
  # setup special environment variable for Appveyor CI test environment
  # it is used to disable some tests that can be harmful in this context
  APPVEYOR_CI_ENV: 1

  # setup tests matrix
  matrix:
    # - PYTHON: "C:\\Python35-x64"
    #   PYTHON_VERSION: "3.5.3"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

# check current python version
init:
  - "echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

# command to install system and python dependencies
install:
  - "cinst ffmpeg"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

# command to run tests
test_script:
  - "cd dakara_server && %PYTHON%/python.exe ./manage.py test -v 2"
  - "cd"
  - "cd dakara_server && %PYTHON%/Scripts/pytest.exe -v"
  - "%PYTHON%/Scripts/flake8.exe"
