# Configuration file for nginx
# `daphne.conf` is the actual configuration that should be maintained by the user
# `daphne.conf.sample` is the default configuration which is updated automatically
# Note: enter here the command-line arguments you want to add
