# Configuration file for nginx main file
# `nginx_main.conf` is the actual configuration that should be maintained by the user
# `nginx_main.conf.sample` is the default configuration which is updated automatically

worker_processes 4;
