pid /var/run/nginx.pid;
daemon off;

events {}

http {
    include mime.types;

    # user custom config
    include /data/config/nginx_server.conf;
}

# user custom config
include /data/config/nginx_main.conf;
