pid /var/run/nginx.pid;
daemon off;

events {}

http {
    include mime.types;

    server {
        listen 80;

        gzip on;
        gunzip on;
        gzip_types text/plain
                   text/css
                   text/js
                   text/xml
                   text/javascript
                   application/javascript
                   application/json
                   application/rss+xml
                   image/svg+xml;

        root /app/static/;
        index index.html;

        location /static/ {
            alias /app/static/;
        }

        location / {
            try_files $uri $uri/ /index.html;

            location ~^/(api|admin) {
                proxy_pass http://localhost:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
            }

            location /ws {
                proxy_pass http://localhost:8001;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_connect_timeout 70s;
                proxy_send_timeout 70s;
                proxy_read_timeout 70s;
            }
        }
    }
}

# user custom config
include /data/config/nginx.conf;
