version: "2.2"

services:
  mysql:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_DATABASE: "dakara"
    restart: "unless-stopped"

  redis:
    image: redis:latest
    restart: "unless-stopped"

  dakara-server:
    image: dakara-server:latest
    volumes:
      - dakara_server_data:/data
    environment:
      DAKARA_DATABASE_URL: "mysql://user:password@mysql/dakara"
      DAKARA_REDIS_URL: "redis://redis"
      DAKARA_ALLOWED_HOSTS: "localhost,example.com"
      DAKARA_HOST_URL: "http://example.com"
      DAKARA_SECRET_KEY: "your-secret-key"
      DAKARA_LANGUAGE_CODE: "en-us"
      DAKARA_TIME_ZONE: "UTC"
      DAKARA_LOG_LEVEL: "INFO"
      DAKARA_EMAIL_ENABLED: true # or false
      DAKARA_EMAIL_HOST: "postfix"
      DAKARA_EMAIL_HOST_USER: "user"
      DAKARA_EMAIL_HOST_PASSWORD: "password"
      DAKARA_SENDER_EMAIL: "no-reply@example.com"
    restart: "unless-stopped"
    ports:
      - 80
    depends_on:
      - mysql
      - redis

volume:
  dakara_server_data:
  mysql_data:
