---

# This file is an example and should be adapted to your needs.
# You may be interested to use an `.env` file to keep secrets:
# https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/

services:
  # database server
  database:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_DATABASE: "dakara"
    restart: "unless-stopped"

  # cache server
  cache:
    image: redis:latest
    restart: "unless-stopped"

  # websocket server (and base configuration)
  websocket: &base
    image: dakaraproject/dakaraserver:latest
    volumes:
      - dakara_server_data:/data
    environment:
      # Database configuration as a URL
      # Main patterns are:
      #   postgres://user:password@host:port/name PostgreSQL
      #   mysql://user:password@host:port/name MySQL (using the C driver, not
      #     available in the image)
      #   mysql-connector://user:password@host:port/name MySQL (using the
      #     Python driver)
      #   sqlite://path SQLite
      # Check https://github.com/jazzband/dj-database-url#url-schema for
      #   documentation
      DAKARA_DATABASE_URL: "mysql-connector://user:password@database:3306/dakara"

      # Cache configuration as a URL
      # Note that only Redis is supported
      # DAKARA_REDIS_URL: "redis://cache:6379"

      # Allowed hosts
      DAKARA_ALLOWED_HOSTS: "localhost,example.com"

      # URL of the host
      DAKARA_HOST_URL: "http://example.com"

      # Extra CSRF trusted origins
      # Note that DAKARA_HOST_URL is already accounted for
      # DAKARA_CSRF_TRUSTED_ORIGINS: "http://other.example.com,http://extra.exmaple.com"

      # Secret key of the instance
      # Note that it must be secret
      DAKARA_SECRET_KEY: "your-secret-key"

      # Admin account credentials
      # Note that the admin account should be only used to create managers, and
      #   deleted afterward for security reasons
      # DAKARA_SUPERUSER_USERNAME: "admin"
      # DAKARA_SUPERUSER_EMAIL: "admin@localhost"
      DAKARA_SUPERUSER_PASSWORD: "admin-password"

      # Hard limit for the maximum size of the playlist
      # DAKARA_PLAYLIST_SIZE_LIMIT: 1000

      # Interval for the scheduler (in minutes)
      # DAKARA_SCHEDULER_INTERVAL: 5

      # Django time zone
      DAKARA_TIME_ZONE: "UTC"

      # Allow the instance to send emails
      DAKARA_EMAIL_ENABLED: false

      # Email configuration as a URL
      # Note that this setting is ineffective if DAKARA_EMAIL_ENABLED is false
      # Main pattern are:
      #   smtp://user:password@host:port SMTP with no SSL
      #   submission://user:password@host:port SMTP with STARTTLS
      # Check https://github.com/migonzalvar/dj-email-url#supported-backends
      #   for documentation
      DAKARA_EMAIL_URL: "smtp://user:password@mail:25"

      # Email SSL files
      # Note that this setting is ineffective if DAKARA_EMAIL_ENABLED is false
      # DAKARA_EMAIL_SSL_KEYFILE: ""
      # DAKARA_EMAIL_SSL_CERTIFICATE: ""

      # Sender address for the emails of the instance
      # Note that this setting is ineffective if DAKARA_EMAIL_ENABLED is false
      DAKARA_SENDER_EMAIL: "no-reply@example.com"

      # Log level of the instance
      # DAKARA_LOG_LEVEL: "INFO"

      # Log events directly to the console
      DAKARA_LOG_TO_CONSOLE: false

      # Logfile location
      # Note that this setting is ineffective if DAKARA_LOG_TO_CONSOLE is true
      # DAKARA_LOG_FILE_PATH: "/data/logs/dakara_server.log"

      # Logfile maximum size
      # Note that this setting is ineffective if DAKARA_LOG_TO_CONSOLE is true
      # DAKARA_LOG_FILE_MAX_SIZE: 1000000

      # Logfile number of backups
      # Note that this setting is ineffective if DAKARA_LOG_TO_CONSOLE is true
      # DAKARA_LOG_FILE_BACKUP_COUNT: 2

      # Django language
      # DAKARA_LANGUAGE_CODE: "en-us"
    restart: "unless-stopped"
    depends_on:
      - database
      - cache
    healthcheck: &healthcheck
      test: ["CMD", "check_health_websocket.sh"]
      interval: 5m
      start_interval: 5s
      start_period: 30s
    command: "run_websocket_daphne.sh"

  # api server
  api:
    <<: *base
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "check_health_api.sh"]
    command: "run_api_gunicorn.sh"

  # scheduler for tasks
  scheduler:
    <<: *base
    healthcheck:
      disable: true
    command: "run_scheduler_apscheduler.sh"

  # web server (main entrygate)
  web:
    <<: *base
    depends_on:
      - websocket
      - api
      - scheduler
    ports:
      - 80:80
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "check_health_web.sh"]
    command: "run_web_nginx.sh"

volumes:
  dakara_server_data:
  mysql_data:
