# This file is an example and should be adapted to your needs.
# You may be interested to use an `.env` file to keep secrets:
# https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/

services:
  # database server
  mysql:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_DATABASE: "dakara"
    restart: "unless-stopped"

  # cache server
  redis:
    image: redis:latest
    restart: "unless-stopped"

  # websocket server (and base configuration)
  daphne: &dakara-server
    image: dakara-server:latest
    volumes:
      - dakara_server_data:/data
    environment:
      DAKARA_DATABASE_URL: "mysql-connector://user:password@mysql:3306/dakara"
      # DAKARA_REDIS_URL: "redis://redis:6379"
      DAKARA_ALLOWED_HOSTS: "localhost,example.com"
      DAKARA_HOST_URL: "http://example.com"
      DAKARA_CSRF_TRUSTED_ORIGINS: "http://localhost"
      DAKARA_SECRET_KEY: "your-secret-key"
      # DAKARA_SUPERUSER_USERNAME: "admin"
      # DAKARA_SUPERUSER_EMAIL: "admin@localhost"
      DAKARA_SUPERUSER_PASSWORD: "admin-password"
      # DAKARA_LANGUAGE_CODE: "en-us"
      # DAKARA_TIME_ZONE: "UTC"
      # DAKARA_LOG_LEVEL: "INFO"
      DAKARA_EMAIL_ENABLED: true
      DAKARA_EMAIL_URL: "smtp://user:password@postfix:25"
      DAKARA_SENDER_EMAIL: "no-reply@example.com"
      DAKARA_LOG_TO_CONSOLE: false
      # DAKARA_LOG_FILE_PATH: "/data/logs/dakara_server.log"
      # DAKARA_LOG_FILE_MAX_SIZE: 1000000
      # DAKARA_LOG_FILE_BACKUP_COUNT: 2
    restart: "unless-stopped"
    depends_on:
      - mysql
      - redis
    command: "daphne.sh"

  # api server
  gunicorn:
    <<: *dakara-server
    command: "gunicorn.sh"

  # scheduler for tasks
  apscheduler:
    <<: *dakara-server
    command: "apscheduler.sh"

  # web server (main entrygate)
  nginx:
    <<: *dakara-server
    depends_on:
      - daphne
      - gunicorn
      - apscheduler
    command: "nginx.sh"
    ports:
      - 8080:80

volumes:
  dakara_server_data:
  mysql_data:
