# Generated by Django 1.11.13 on 2018-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlist", "0004_playlist_entry_past")]
    replaces = [("playlist", "0005_auto_20180610_1705")]

    operations = [
        migrations.AlterModelOptions(
            name="playlistentry", options={"ordering": ("order",)}
        ),
        migrations.AddField(
            model_name="playlistentry",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
