# Generated by Django 3.2.12 on 2022-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0014_player_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karaoke",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="playererror",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="playlistentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
