# Generated by Django 3.2.12 on 2022-04-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0015_id_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlistentry",
            old_name="date_played",
            new_name="date_play",
        ),
    ]
