# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 08:34
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20180518_1532")]

    operations = [
        migrations.AlterField(
            model_name="dakarauser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username "
                                "already exists."},
                help_text="Required. 150 characters or fewer. "
                          "Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.
                            UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        )
    ]
