# Generated by Django 2.2.11 on 2020-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_dakara_user_username"),
    ]
    replaces = [
        ("users", "0004_auto_20200329_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dakarauser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
