# Generated by Django 2.2.13 on 2020-10-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200329_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="dakarauser",
            name="validated_by_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dakarauser",
            name="validated_by_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dakarauser",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
