#!/bin/bash

HOOKS_DIR=$(dirname $(readlink -f $0))
HOOKS_PRE_COMMIT_DIR="$HOOKS_DIR/pre-commit.d"

returned_value=0

# scan the pre-commit hooks dir
for file in $HOOKS_PRE_COMMIT_DIR/*
do
        # exclude non executable file
        if [[ ! -x $file ]]
        then
                echo "Skipping '$(basename $file)'"
                continue
        fi

        # run the hook
        $file
        returned_value=$((returned_value + $?))
done

if [[ $returned_value -gt 0 ]]
then
    >&2 echo "Commit denied, there were failures."
    exit 1
fi

exit 0
