#!/bin/bash

PYTHON_MAJOR=$(python -c "import sys;print(sys.version_info.major)")
PYTHON_MINOR=$(python -c "import sys;print(sys.version_info.minor)")

if [[ $PYTHON_MAJOR == 3 && $PYTHON_MINOR < 6 ]]
then
        echo "Skipping this test as it requires at least Python 3.6"
        exit 0
fi

git diff --cached --name-only --diff-filter=ACMR | \
    /bin/grep "\.py$" | \
    xargs black --check
